---
driver:
  name: terraform
  root_module_directory: test/fixtures
  parallelism: 4
  verify_version: false

provisioner:
  name: terraform

platforms:
  - name: gcp

suites:
  - name: single-project
    driver:
      root_module_directory: test/fixtures/single-project
  - name: single-project-k8s
    driver:
      root_module_directory: test/fixtures/single-project-k8s
  - name: organization
    driver:
      root_module_directory: test/fixtures/organization

# this test does not make sense, since its the same as the organization
# besides, with org compliance, but on both tests
#  - name: organization-optimized-compliance
#    driver:
#      root_module_directory: test/fixtures/organization-org_compliance
