repos:
  # https://github.com/antonbabenko/pre-commit-terraform/blob/master/README.md#terraform_validate (point 4)
  - repo: local
    hooks:
      - id: terraform_clean
        name: "Terraform Cleanup"
        pass_filenames: false
        language: system
        entry: bash -c "find . \( -iname ".terraform*" ! -iname ".terraform-docs*" ! -path "*/test/*" \)  -print0 | xargs -0 rm -r; true"

  - repo: local
    # https://github.com/antonbabenko/pre-commit-terraform/#terraform_validate
    # Adding this patch to fix organizational multi-provider terraform validate error
    # 'missing provider provider["registry.terraform.io/hashicorp/google"].multiproject'
    hooks:
      - id: generate-terraform-providers
        name: generate-terraform-providers
        require_serial: true
        always_run: true
        entry: ./examples/organization/.generate-providers.sh
        language: script
        pass_filenames: false

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.64.0
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_docs
        args:
          - '--args=--sort-by required'
      - id: terraform_tflint
        exclude: (test)|(examples-internal)\/.*$|(examples/organization)
        args:
          - '--args=--only=terraform_deprecated_interpolation'
          - '--args=--only=terraform_deprecated_index'
          - '--args=--only=terraform_unused_declarations'
          - '--args=--only=terraform_comment_syntax'
          - '--args=--only=terraform_documented_outputs'
          - '--args=--only=terraform_documented_variables'
          - '--args=--only=terraform_typed_variables'
          - '--args=--only=terraform_module_pinned_source'
          - '--args=--only=terraform_naming_convention'
          - '--args=--only=terraform_required_version'
          - '--args=--only=terraform_required_providers'
          - '--args=--only=terraform_standard_module_structure'
          - '--args=--only=terraform_workspace_remote'
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
